export const SUPPORTED_HARNESSES = [
  'hermes',
  'claude-code',
  'claude',
  'codex',
  'gemini',
  'opencode',
  'openclaw',
  'custom',
];

function clean(value, fallback = '') {
  const v = value == null ? '' : String(value).trim();
  return v || fallback;
}

export function normalizeInstallAnswers(input = {}) {
  const harness = clean(input.harness || input.AGENT_BACKEND, 'hermes').toLowerCase();
  const normalizedHarness = SUPPORTED_HARNESSES.includes(harness) ? harness : 'custom';
  const out = {
    AGENT_BACKEND: normalizedHarness,
    DISCORD_BOT_TOKEN: clean(input.discordBotToken || input.DISCORD_BOT_TOKEN),
    DISCORD_ALLOWED_USERS: clean(input.allowedUsers || input.DISCORD_ALLOWED_USERS),
    AUTO_JOIN_VOICE_CHANNELS: clean(input.autoJoinVoiceChannels || input.AUTO_JOIN_VOICE_CHANNELS, '일반,General,general'),
    TRANSCRIPT_CHANNEL_ID: clean(input.transcriptChannelId || input.TRANSCRIPT_CHANNEL_ID),
    TTS_BACKEND: ['edge', 'openvoice'].includes(clean(input.ttsBackend || input.TTS_BACKEND, 'edge').toLowerCase())
      ? clean(input.ttsBackend || input.TTS_BACKEND, 'edge').toLowerCase()
      : 'edge',
    TTS_VOICE: clean(input.ttsVoice || input.TTS_VOICE, 'ko-KR-SunHiNeural'),
    TTS_RATE: clean(input.ttsRate || input.TTS_RATE, '+10%'),
    TTS_MAX_CHARS: clean(input.ttsMaxChars || input.TTS_MAX_CHARS, '495'),
    OPENVOICE_DIR: clean(input.openvoiceDir || input.OPENVOICE_DIR, './vendor/OpenVoice'),
    OPENVOICE_VENV: clean(input.openvoiceVenv || input.OPENVOICE_VENV, './.venv-openvoice'),
    OPENVOICE_REF_AUDIO: clean(input.openvoiceRefAudio || input.OPENVOICE_REF_AUDIO, './voice-samples/user-reference.wav'),
    OPENVOICE_LANGUAGE: clean(input.openvoiceLanguage || input.OPENVOICE_LANGUAGE, 'KR'),
    OPENVOICE_STYLE: clean(input.openvoiceStyle || input.OPENVOICE_STYLE, 'default'),
    OPENVOICE_TIMEOUT_MS: clean(input.openvoiceTimeoutMs || input.OPENVOICE_TIMEOUT_MS, '90000'),
    OPENVOICE_PROGRESS: input.openvoiceProgress === true || input.OPENVOICE_PROGRESS === '1' ? '1' : '0',
    REQUIRE_WAKE_WORD: input.requireWakeWord === true || input.REQUIRE_WAKE_WORD === '1' ? '1' : '0',
    MIN_UTTERANCE_SECONDS: clean(input.minUtteranceSeconds || input.MIN_UTTERANCE_SECONDS, '1.0'),
    UTTERANCE_IDLE_MS: clean(input.utteranceIdleMs || input.UTTERANCE_IDLE_MS, '2000'),
    HERMES_TASK_TIMEOUT_MS: clean(input.taskTimeoutMs || input.HERMES_TASK_TIMEOUT_MS, '0'),
    HERMES_CHAT_TIMEOUT_MS: clean(input.chatTimeoutMs || input.HERMES_CHAT_TIMEOUT_MS, '45000'),
    AGENT_VERBOSE_PROGRESS: input.verboseProgress === true || input.AGENT_VERBOSE_PROGRESS === '1' ? '1' : '0',
    LATENCY_LOG_PATH: clean(input.latencyLogPath || input.LATENCY_LOG_PATH, './.logs/latency.jsonl'),
  };
  if (input.agentLabel || input.AGENT_LABEL) out.AGENT_LABEL = clean(input.agentLabel || input.AGENT_LABEL);
  if (input.agentCommand || input.AGENT_COMMAND) out.AGENT_COMMAND = clean(input.agentCommand || input.AGENT_COMMAND);
  return out;
}

function quoteEnv(value) {
  return JSON.stringify(String(value ?? ''));
}

export function buildEnvFile(values = {}) {
  const ordered = [
    'DISCORD_BOT_TOKEN',
    'DISCORD_ALLOWED_USERS',
    'AUTO_JOIN_VOICE_CHANNELS',
    'TRANSCRIPT_CHANNEL_ID',
    'AGENT_BACKEND',
    'AGENT_LABEL',
    'AGENT_COMMAND',
    'TTS_BACKEND',
    'TTS_VOICE',
    'TTS_RATE',
    'TTS_MAX_CHARS',
    'OPENVOICE_DIR',
    'OPENVOICE_VENV',
    'OPENVOICE_REF_AUDIO',
    'OPENVOICE_LANGUAGE',
    'OPENVOICE_STYLE',
    'OPENVOICE_TIMEOUT_MS',
    'OPENVOICE_PROGRESS',
    'REQUIRE_WAKE_WORD',
    'MIN_UTTERANCE_SECONDS',
    'UTTERANCE_IDLE_MS',
    'HERMES_TASK_TIMEOUT_MS',
    'HERMES_CHAT_TIMEOUT_MS',
    'AGENT_VERBOSE_PROGRESS',
    'LATENCY_LOG_PATH',
  ];
  const lines = [
    '# Generated by VerbalCoding installer.',
    '# Secrets stay local; do not commit this file.',
  ];
  for (const key of ordered) {
    if (values[key] == null || values[key] === '') continue;
    lines.push(`${key}=${quoteEnv(values[key])}`);
  }
  return `${lines.join('\n')}\n`;
}

export function parseKeyValueEnv(text) {
  const out = {};
  for (const raw of String(text || '').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const idx = line.indexOf('=');
    const key = line.slice(0, idx).trim().replace(/^export\s+/, '');
    let value = line.slice(idx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    try {
      if (line.slice(idx + 1).trim().startsWith('"')) value = JSON.parse(line.slice(idx + 1).trim());
    } catch {}
    out[key] = value;
  }
  return out;
}

export function renderInstallSummary(values = {}) {
  const backend = values.AGENT_BACKEND || 'hermes';
  return [
    `Configured Discord voice bridge for harness: ${backend}`,
    '',
    'Next commands:',
    '  npm install',
    '  ./run.sh',
    '',
    `Auto-join voice channels: ${values.AUTO_JOIN_VOICE_CHANNELS || '일반,General,general'}`,
    `TTS backend: ${values.TTS_BACKEND || 'edge'}`,
    `Verbose progress: ${values.AGENT_VERBOSE_PROGRESS === '1' ? 'on' : 'off'} (toggle later with !verbose on/off)`,
    'Use !ask <text>, !session, !reset-session, !join, !leave, !verbose, !voice-test, and !sensitivity in Discord.',
  ].join('\n');
}
